services:
  db:
    image: mysql:5.7
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Senha123
      MYSQL_DATABASE: meubanco
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  app:
    build: ./app
    restart: always
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: Senha123
      DB_NAME: meubanco
    depends_on:
      - db
    networks:
      - app-network

  nginx:
    build: ./nginx
    restart: always
    ports:
      - "4500:80"
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
